### ISSUE TITLE
Using Ada in Visual Studio

### ISSUE THREAD

**Issue by simonpalmer1964** [AdaCore/ada_language_server#1007]
Hello,
I have just installed the following extensions in Visual Studio
1. Language Support for Ada
2. Language SUpport for Ada with debug info
3. Native Debug

I get the following error
Error: command 'als-other-file' already exists
	at o.registerCommand (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:61206)
	at Object.registerCommand (/snap/code/102/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:30919)
	at Ta.register (/home/simon/.vscode/extensions/adacore.ada-debug-23.0.8/out/extension.js:34:44070)
	at Ta.initialize (/home/simon/.vscode/extensions/adacore.ada-debug-23.0.8/out/extension.js:34:43649)
	at lc.initializeFeatures (/home/simon/.vscode/extensions/adacore.ada-debug-23.0.8/out/extension.js:36:12865)
	at /home/simon/.vscode/extensions/adacore.ada-debug-23.0.8/out/extension.js:36:5960

Any help greatly appreciated

**Comment by reznikmm** [comment]
You can't have both "Language Support for Ada" and "Language Support for Ada with debug info" installed at the same time :disappointed:  These are the same application. "Language Support for Ada with debug info" is just for internal debugging, because it includes debugging information, while "Language Support for Ada" is an optimized and stripped version.

**Comment by simonpalmer1964** [comment]
Thanks Max,

I realised that and removed the “Language support for Ada” version, all good now.

Cheers
Simon
