### ISSUE TITLE
installing vs code extention mac os catalina

### ISSUE THREAD

**Issue by Dominikskeries** [AdaCore/ada_language_server#1102]
when i try to install it i get this error 
[error] Internal: Unable to install the extension. Please Quit and Start VS Code before reinstalling.
    at Y.n (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:165548)
    at async Y.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167256)

**Comment by AnthonyLeonardoGracio** [comment]
Hello!

I have tested with VS Code 1.75.0 and everything works fine when installing from the Marketplace. Make sure to update VS Code if it's not up-to-date. 

I'll close the issue, but re-open it with more information (VS Code and extension versions etc) if you still have problems.
