### ISSUE TITLE
Language Support for Ada (with debug info) v23.0.11 "Error: command 'als-other-file' already exists"

### ISSUE THREAD

**Issue by docdoob** [AdaCore/ada_language_server#1193]
This error message occurs repeatedly.  I have the "Ada & SPARK" extension installed also.  The full message is as follows:
[Error - 18:00:12] Notify file events failed.
Error: command 'als-other-file' already exists
	at d.registerCommand (/snap/code/157/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:185480)
	at Object.registerCommand (/snap/code/157/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:21988)
	at Ta.register (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:34:44070)
	at Ta.initialize (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:34:43649)
	at lc.initializeFeatures (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:36:12865)
	at /home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:36:5960
[Error - 18:00:38] Notify file events failed.
Error: command 'als-other-file' already exists
	at d.registerCommand (/snap/code/157/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:185480)
	at Object.registerCommand (/snap/code/157/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:21988)
	at Ta.register (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:34:44070)
	at Ta.initialize (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:34:43649)
	at lc.initializeFeatures (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:36:12865)
	at /home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:36:5960
[Error - 18:00:59] Notify file events failed.
Error: command 'als-other-file' already exists
	at d.registerCommand (/snap/code/157/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:152:185480)
	at Object.registerCommand (/snap/code/157/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:21988)
	at Ta.register (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:34:44070)
	at Ta.initialize (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:34:43649)
	at lc.initializeFeatures (/home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:36:12865)
	at /home/john/.vscode/extensions/adacore.ada-debug-23.0.11/out/extension.js:36:5960

**Comment by eliericha** [comment]
Hello @docdoob ,

Thank you for reporting this issue. However I notice from the backtrace that you are using the extension with identifier `adacore.ada-debug` which is an old version called `Language Support for Ada (with debug info)` that has not been updated in a long time on the marketplace.

The extension that should be used is now called `Ada & SPARK` and can be found [here](https://marketplace.visualstudio.com/items?itemName=AdaCore.ada).

In your message you indicate that you have both extensions installed, so that is the source of the problem. I suggest that you uninstall `Language Support for Ada (with debug info)`. Only the new `Ada & SPARK` extension should be installed.

Internally I am looking into what should be done with the old extension. We will either update it or remove it altogether if not useful.

Out of curiosity, how did you end up on the old `Language Support for Ada (with debug info)` extension? Is there a stale hyperlink somewhere still pointing to it?
